version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run: npm install --save-dev firebase-tools
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build application
          command: npm run build
      - store_artifacts:
          path: build

  test:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - attach_artifacts: at build
      - run:
          name: Execute automated tests
          command: npm run test

  deploy-to-staging:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - attach_artifacts: at build
      - run:
          name: Enable Firebase webframeworks
          command: ./node_modules/.bin/firebase experiments:enable webframeworks
      - run:
          name: Deploy app to Firebase staging environment
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project staging

  deploy-to-production:
    working_directory: ~/project
    docker:
      - image: cimg/node:18.17.0
    steps:
      - checkout
      - attach_artifacts: at build
      - run:
          name: Enable Firebase webframeworks
          command: ./node_modules/.bin/firebase experiments:enable webframeworks
      - run:
          name: Deploy app to Firebase production environment
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project production

workflows:
  build-test-stage-approve-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-to-staging:
          requires:
            - test
      - wait-approval:
          type: approval
          requires:
            - deploy-to-staging
      - deploy-to-production:
          requires:
            - wait-approval
